provider "aws" {
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region = "${var.region}"
}
# VPC
resource "aws_vpc" "vpc-step" {
    cidr_block = "172.16.0.0/21"
    instance_tenancy = "default"
    enable_dns_support = "true"
    enable_dns_hostnames = "false"
    tags = {
      Name = "vpc-step"
    }
}
# インターネットゲートウェイ
resource "aws_internet_gateway" "igw-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    depends_on = [aws_vpc.vpc-step]
    tags = {
      Name = "igw-step"
    }
}
# サブネット
resource "aws_subnet" "pub-a-subnet-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    cidr_block = "172.16.1.0/24"
    availability_zone = "ap-northeast-1a"
    tags = {
      Name = "pub-a-subnet-step"
    }
}
resource "aws_subnet" "pub-c-subnet-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    cidr_block = "172.16.2.0/24"
    availability_zone = "ap-northeast-1c"
    tags = {
      Name = "pub-c-subnet-step"
    }
}
resource "aws_subnet" "private-a-subnet-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    cidr_block = "172.16.3.0/24"
    availability_zone = "ap-northeast-1a"
    tags = {
      Name = "private-a-subnet-step"
    }
}
resource "aws_subnet" "private-c-subnet-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    cidr_block = "172.16.4.0/24"
    availability_zone = "ap-northeast-1c"
    tags = {
      Name = "private-c-subnet-step"
    }
}
resource "aws_subnet" "privateII-a-subnet-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    cidr_block = "172.16.5.0/24"
    availability_zone = "ap-northeast-1a"
    tags = {
      Name = "privateII-a-subnet-step"
    }
}
# ルートテーブル
resource "aws_route_table" "rtb-step" {
    vpc_id = "${aws_vpc.vpc-step.id}"
    route {
        cidr_block = "0.0.0.0/0"
        gateway_id = "${aws_internet_gateway.igw-step.id}"
    }
    tags = {
      Name = "rtb-step"
    }
}
# ルートテーブルのサブネット関連付け
resource "aws_route_table_association" "public_1a" {
    route_table_id = "${aws_route_table.rtb-step.id}"
    subnet_id = "${aws_subnet.pub-a-subnet-step.id}"
}
resource "aws_route_table_association" "public_1c" {
    route_table_id = "${aws_route_table.rtb-step.id}"
    subnet_id = "${aws_subnet.pub-c-subnet-step.id}"
}
resource "aws_route_table_association" "private_1a" {
    route_table_id = "${aws_route_table.rtb-step.id}"
    subnet_id = "${aws_subnet.private-a-subnet-step.id}"
}
resource "aws_route_table_association" "private_1c" {
    route_table_id = "${aws_route_table.rtb-step.id}"
    subnet_id = "${aws_subnet.private-c-subnet-step.id}"
}
resource "aws_route_table_association" "privateII_1a" {
    route_table_id = "${aws_route_table.rtb-step.id}"
    subnet_id = "${aws_subnet.privateII-a-subnet-step.id}"
}
# セキュリティグループ
resource "aws_security_group" "scg-step-bastion" {
    name = "scg-step-bastion"
    description = "This security group was generated by AWS Marketplace and is based on recommended settings for LAMP Stack CentOS 7 version 20210403 provided by Supported Images"
    vpc_id = "${aws_vpc.vpc-step.id}"
    ingress {
        from_port = 22
        to_port = 22
        protocol = "tcp"
        cidr_blocks = ["182.168.33.163/32"]
        description = ""
    }
    ingress {
        from_port = 49222
        to_port = 49222
        protocol = "tcp"
        cidr_blocks = ["182.168.33.163/32"]
        description = ""
    }
    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
        description = ""
    }
    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
        description = ""
    }
    tags = {
      Name = "step-bastion"
    }
}
resource "aws_security_group" "scg-stepweb1" {
    name = "scg-stepweb1"
    description = "launch-wizard-1 created 2022-02-26T16:59:35.808+09:00"
    vpc_id = "${aws_vpc.vpc-step.id}"
    ingress {
        from_port = 49222
        to_port = 49222
        protocol = "tcp"
        security_groups = [aws_security_group.scg-step-bastion.id]
        description = ""
    }
    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
        description = ""
    }
    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
        description = ""
    }
    tags = {
      Name = "step-web1"
    }
}
resource "aws_security_group" "scg_alb-step" {
    name = "scg_alb-step"
    description = "scg_alb-step"
    vpc_id = "${aws_vpc.vpc-step.id}"
    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
        ipv6_cidr_blocks = ["::/0"]
        description = ""
    }
    ingress {
        from_port = 443
        to_port = 443
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
        ipv6_cidr_blocks = ["::/0"]
        description = ""
    }
    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
        description = ""
    }
    tags = {
      Name = "step-alb"
    }
}
resource "aws_security_group" "scg-rds-step" {
    name = "scg-rds-step"
    description = "step-rds"
    vpc_id = "${aws_vpc.vpc-step.id}"
    ingress {
        from_port = 3306
        to_port = 3306
        protocol = "tcp"
        security_groups = [aws_security_group.scg-stepweb1.id]
        description = ""
    }
    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
        description = ""
    }
    tags = {
      Name = "step-rds"
    }
}
# インスタンス
resource "aws_instance" "step-web1" {
    ami = "${var.images.step-web1}"
    instance_type = "t2.micro"
    key_name = "key-step-bastion"
    vpc_security_group_ids = [
      "${aws_security_group.scg-stepweb1.id}"
    ]
    subnet_id = "${aws_subnet.private-a-subnet-step.id}"
    associate_public_ip_address = "true"
    root_block_device {
      volume_type = "gp2"
      volume_size = "30"
      delete_on_termination = false
      tags = {
        Name = "step-web1"
      }
    }
    tags = {
        Name = "step-web1"
    }
}
resource "aws_instance" "step-bastion" {
    ami = "${var.images.step-bastion}"
    instance_type = "t2.micro"
    key_name = "key-step-bastion"
    vpc_security_group_ids = [
      "${aws_security_group.scg-step-bastion.id}"
    ]
    subnet_id = "${aws_subnet.pub-c-subnet-step.id}"
    associate_public_ip_address = "true"
    root_block_device {
      volume_type = "gp2"
      volume_size = "30"
      delete_on_termination = false
      tags = {
        Name = "step-bastion"
      }
    }
    tags = {
        Name = "step-bastion"
    }
}